/**
 * R46 Template Helpers
 *
 * Uses the downloaded n8n template as the source of truth for platform wiring:
 * form labels, Apify actor IDs, field-mapping assignments, and output sheet names.
 *
 * Input builders are implemented locally so this module does not depend on n8n at runtime.
 */
import { readFile } from 'fs/promises';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export const TEMPLATE_ASSET_PATH = join(__dirname, 'assets', 'original', 'ultimate-extract-r46.n8n.json');

const PLATFORM_ID_ALIASES = new Map([
  ['Meta Ads', 'meta-ads'],
  ['Tiktok', 'tiktok'],
  ['Instagram', 'instagram'],
  ['YouTube Long', 'youtube-longs'],
  ['YouTube Longs', 'youtube-longs'],
  ['YouTube', 'youtube-longs'],
  ['YouTube Shorts', 'youtube-shorts'],
  ['LinkedIn', 'linkedin'],
  ['X / Twitter', 'x-twitter'],
  ['X/Twitter', 'x-twitter'],
  ['Twitter', 'x-twitter'],
  ['Reddit', 'reddit'],
]);

function slugify(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export function normalizePlatformId(value) {
  return PLATFORM_ID_ALIASES.get(value) || slugify(value);
}

function buildMetaAdsInput({ searchTerm, maxItems }) {
  return {
    limitPerSource: maxItems,
    scrapeAdDetails: true,
    'scrapePageAds.activeStatus': 'all',
    'scrapePageAds.countryCode': 'ALL',
    urls: [
      {
        url: `https://www.facebook.com/ads/library/?active_status=all&ad_type=all&country=ALL&is_targeted_country=false&media_type=all&q=${encodeURIComponent(searchTerm)}&search_type=keyword_unordered`,
      },
    ],
  };
}

const ACTOR_INPUT_BUILDERS = {
  'meta-ads': buildMetaAdsInput,
  tiktok: ({ searchTerm, maxItems }) => ({
    excludePinnedPosts: false,
    oldestPostDateUnified: '2019-01-01',
    proxyCountryCode: 'None',
    resultsPerPage: maxItems,
    scrapeRelatedVideos: false,
    searchQueries: [searchTerm],
    shouldDownloadAvatars: false,
    shouldDownloadCovers: false,
    shouldDownloadMusicCovers: false,
    shouldDownloadSlideshowImages: false,
    shouldDownloadSubtitles: true,
    shouldDownloadVideos: false,
  }),
  instagram: ({ searchTerm, maxItems }) => ({
    hashtags: [searchTerm.replace(/\s+/g, '_')],
    keywordSearch: true,
    resultsLimit: maxItems,
  }),
  'youtube-longs': ({ searchTerm, maxItems }) => ({
    downloadSubtitles: true,
    hasCC: false,
    hasLocation: false,
    hasSubtitles: false,
    is360: false,
    is3D: false,
    is4K: false,
    isBought: false,
    isHD: false,
    isHDR: false,
    isLive: false,
    isVR180: false,
    maxResultStreams: 0,
    maxResults: maxItems,
    maxResultsShorts: 1,
    preferAutoGeneratedSubtitles: false,
    saveSubsToKVS: false,
    searchQueries: [searchTerm],
  }),
  'youtube-shorts': ({ searchTerm, maxItems }) => ({
    downloadSubtitles: true,
    hasCC: false,
    hasLocation: false,
    hasSubtitles: false,
    is360: false,
    is3D: false,
    is4K: false,
    isBought: false,
    isHD: false,
    isHDR: false,
    isLive: false,
    isVR180: false,
    maxResultStreams: 0,
    maxResults: 0,
    maxResultsShorts: maxItems,
    preferAutoGeneratedSubtitles: false,
    saveSubsToKVS: false,
    searchQueries: [searchTerm],
  }),
  linkedin: ({ searchTerm, maxItems }) => ({
    keyword: searchTerm,
    limit: maxItems,
  }),
  'x-twitter': ({ searchTerm, maxItems }) => ({
    maxItems,
    searchTerms: [searchTerm],
  }),
  reddit: ({ searchTerm, maxItems }) => ({
    debugMode: false,
    ignoreStartUrls: false,
    includeNSFW: true,
    maxItems,
    proxy: {
      useApifyProxy: true,
      apifyProxyGroups: ['RESIDENTIAL'],
    },
    scrollTimeout: 40,
    searchComments: false,
    searchCommunities: false,
    searchPosts: true,
    searchUsers: false,
    searches: [searchTerm],
    skipComments: false,
    skipCommunity: false,
    skipUserPosts: false,
    sort: 'relevance',
  }),
};

function getExpressionBody(value) {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  if (trimmed.startsWith('={{') && trimmed.endsWith('}}')) {
    return trimmed.slice(3, -2).trim();
  }
  return null;
}

function evaluateExpression(expression, { rawItem, formData, nowIso }) {
  const scopedLookup = (nodeName) => {
    if (nodeName === 'On form submission') {
      return { item: { json: formData } };
    }
    throw new Error(`Unsupported n8n node lookup in expression: ${nodeName}`);
  };

  // Trusted local lesson asset. We use a tiny expression shim instead of running n8n.
  const evaluator = new Function('$json', '$now', '$', `return (${expression});`);
  return evaluator(rawItem, nowIso, scopedLookup);
}

export function applyFieldAssignments(assignments, rawItem, formData, nowIso = new Date().toISOString()) {
  const fields = {};

  for (const assignment of assignments) {
    const expression = getExpressionBody(assignment.value);
    fields[assignment.name] = expression
      ? evaluateExpression(expression, { rawItem, formData, nowIso })
      : assignment.value;
  }

  return fields;
}

function toNumberOrNull(value) {
  if (value === null || value === undefined || value === '') return null;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function buildNormalizedRecord(platform, fields, rawItem, formData) {
  const postUrl = fields.tiktok_url
    || fields.instagram_url
    || fields.youtube_url
    || fields.linkedin_url
    || fields.x_url
    || fields.reddit_url
    || fields.ad_library_url
    || null;

  return {
    platformId: platform.id,
    platformLabel: platform.label,
    searchTerm: formData['Search for...'],
    maxItemsRequested: formData['How many items to scrape'],
    extractTime: fields.extract_time || new Date().toISOString(),
    title: fields.title || fields.caption || null,
    caption: fields.caption || fields.title || null,
    authorName: fields.username || fields.subreddit || fields.page_name || null,
    authorUrl: fields.userlink || null,
    postUrl,
    publishedAt: fields.date_posted || fields.start_date || null,
    metrics: {
      likes: toNumberOrNull(fields.likes),
      shares: toNumberOrNull(fields.shares),
      comments: toNumberOrNull(fields.comments),
      views: toNumberOrNull(fields.views),
      bookmarks: toNumberOrNull(fields.bookmarks || fields.bookmark),
      upvotes: toNumberOrNull(fields.upvotes),
    },
    sink: {
      documentName: platform.sink.documentName,
      sheetName: platform.sink.sheetName,
    },
    fields,
    raw: rawItem,
  };
}

function buildPlatformSpec({ template, nodeByName, formOptionLabels, filterNode }) {
  const selectedWhen = filterNode.parameters?.conditions?.conditions?.[0]?.rightValue || filterNode.name;
  const actorName = template.connections?.[filterNode.name]?.main?.[0]?.[0]?.node;
  const actorNode = actorName ? nodeByName.get(actorName) : null;
  const transformName = actorName ? template.connections?.[actorName]?.main?.[0]?.[0]?.node : null;
  const transformNode = transformName ? nodeByName.get(transformName) : null;
  const sinkName = transformName ? template.connections?.[transformName]?.main?.[0]?.[0]?.node : null;
  const sinkNode = sinkName ? nodeByName.get(sinkName) : null;

  if (!actorNode || !transformNode || !sinkNode) {
    return null;
  }

  const id = normalizePlatformId(selectedWhen);
  const displayLabel = formOptionLabels.get(id)
    || sinkNode.parameters?.sheetName?.cachedResultName
    || selectedWhen;
  const assignments = transformNode.parameters?.assignments?.assignments || [];
  const sheetSchema = sinkNode.parameters?.columns?.schema || [];
  const buildActorInput = ACTOR_INPUT_BUILDERS[id]
    || (({ searchTerm, maxItems }) => ({
      searchTerm,
      maxItems,
      originalTemplateBody: actorNode.parameters?.customBody || null,
    }));

  return {
    id,
    label: displayLabel,
    optionLabel: displayLabel,
    filter: {
      nodeName: filterNode.name,
      selectedWhen,
    },
    actor: {
      nodeName: actorNode.name,
      actorId: actorNode.parameters?.actorId?.value || null,
      actorStoreUrl: actorNode.parameters?.actorId?.cachedResultUrl || null,
      memoryMb: actorNode.parameters?.memory || null,
      originalTemplateBody: actorNode.parameters?.customBody || null,
    },
    transform: {
      nodeName: transformNode.name,
      assignments,
    },
    sink: {
      nodeName: sinkNode.name,
      documentName: sinkNode.parameters?.documentId?.cachedResultName || sinkNode.parameters?.documentId?.value || null,
      sheetName: sinkNode.parameters?.sheetName?.cachedResultName || sinkNode.parameters?.sheetName?.value || null,
      schema: sheetSchema.length > 0 ? sheetSchema.map(column => column.id) : assignments.map(assignment => assignment.name),
    },
    buildActorInput: (formData) => buildActorInput({
      searchTerm: formData['Search for...'],
      maxItems: formData['How many items to scrape'],
    }),
    normalizeItem: (rawItem, formData, nowIso = new Date().toISOString()) => {
      const fields = applyFieldAssignments(assignments, rawItem, formData, nowIso);
      return buildNormalizedRecord({
        id,
        label: displayLabel,
        sink: {
          documentName: sinkNode.parameters?.documentId?.cachedResultName || null,
          sheetName: sinkNode.parameters?.sheetName?.cachedResultName || null,
        },
      }, fields, rawItem, formData);
    },
  };
}

export async function loadTemplateAsset(templatePath = TEMPLATE_ASSET_PATH) {
  const raw = await readFile(templatePath, 'utf8');
  return JSON.parse(raw);
}

export async function buildTemplateModel(templatePath = TEMPLATE_ASSET_PATH) {
  const template = await loadTemplateAsset(templatePath);
  const nodeByName = new Map(template.nodes.map(node => [node.name, node]));

  const formNode = template.nodes.find(node => node.type === 'n8n-nodes-base.formTrigger');
  const formOptions = formNode?.parameters?.formFields?.values?.find(field => field.fieldLabel === 'Which platforms')?.fieldOptions?.values || [];
  const formOptionLabels = new Map(
    formOptions.map(option => [normalizePlatformId(option.option), option.option])
  );

  const filterNodes = template.nodes.filter(node => node.type === 'n8n-nodes-base.filter');
  const platforms = filterNodes
    .map(filterNode => buildPlatformSpec({ template, nodeByName, formOptionLabels, filterNode }))
    .filter(Boolean);

  return {
    template,
    templatePath,
    lessonName: template.name,
    form: {
      title: formNode?.parameters?.formTitle || 'Ultimate Extract',
      description: formNode?.parameters?.formDescription || '',
      fields: formNode?.parameters?.formFields?.values || [],
    },
    platforms,
  };
}

export function buildFormData(config, templateModel) {
  const platformMap = new Map(templateModel.platforms.map(platform => [platform.id, platform]));
  const selectedLabels = config.platforms
    .map(platformId => platformMap.get(platformId)?.optionLabel)
    .filter(Boolean);

  return {
    'Search for...': config.searchTerm,
    'How many items to scrape': config.maxItems,
    'Which platforms': selectedLabels,
  };
}
